### ISSUE TITLE
Ability to deploy postfacto in k8s

### ISSUE THREAD

**Issue by anoop2811** [pivotal/postfacto#115]
Would be great if there is a helm chart to deploy in kubernetes like in EKS/GKE etc

**Comment by seadowg** [comment]
@anoop2811 would be great to see a PR for this 👍. I know @ipsi did some initial work on investigating what the complexities would be for a Kubernetes deployment.

As a side note: if you are wanting to deploy Postfacto it will be always be simpler to use a CF/Heroku platform if you have access to any of those.

**Comment by anoop2811** [comment]
@seadowg thanks, will try to work on a PR when I have some time. If there is some initial work I can reference, would be great. As an ex pivot, I have used it on PWS before, unfortunately my current needs are to align with corporate needs.

**Comment by crswty** [comment]
Hey, I'm happy to take this if it's not been done yet, I have a working k8s deployment that I'm updating to deploy with Helm. Would have something to test soon.

**Comment by anoop2811** [comment]
@crswty cool, thanks! I haven't started work on it.

**Comment by anoop2811** [comment]
@crswty , just wanted to check if you had made any progress on this

**Comment by crswty** [comment]
Hey, this slipped down my list so apologies for not updating this.

I haven't made much progress on it recently but I did have some work in progress locally that I've pushed 'as is' to this repo [here](https://github.com/crswty/postfacto-helm). It relies on docker images built from this (now very out of date) [branch](https://github.com/crswty/postfacto/commits/wip-dockerize). 

I don't really remember where it is or what else would need to be done to get it working but feel free to take a look and see if it's useful as a starting point for something we could merge back here. The commit before the most recent one is simply deployment manifests which may be a better start point

However, It's probably worth talking about why I stopped making progress on it. I would say that it ended up being more complicated than I was expecting and I think there are a few things I would like to change about the way the main project works first, before creating and maintaining a k8s solution.

1. Coordinating the API & Front End is painful as It is not always clear where the each element will be made available publicly. In the past we have talked about serving the front end from the API, this would massively simplify the deployment for k8s
2. Having to configure where to find the back end means that the front end has to be built when the container starts rather than when it is built, this could be fixed with the same solution as 1. or  worked around by adding some other service.

I'm sure there was some more but that's all I remember for now.

**Comment by crswty** [comment]
So it looks like https://github.com/pivotal/postfacto/pull/174 is getting close. Once that gets merged in I think I'll be able to put together a beta quality chart pretty swiftly.

**Comment by crswty** [comment]
Also requires https://github.com/pivotal/postfacto/issues/191

**Comment by crswty** [comment]
So this has been a long time coming but I'm very happy so say we have a beta Helm Chart and a container available for testing/feedback in [4.1.0](https://github.com/pivotal/postfacto/releases/tag/4.1.0). Further instructions [here](https://github.com/pivotal/postfacto/tree/master/deployment/helm)
