### ISSUE TITLE
Heroku deploy script doesn't work

### ISSUE THREAD

**Issue by mreider** [pivotal/postfacto#137]
Hi there.

A couple of issues.

1. When I try to run the deploy-heroku.sh script it complains about directory references. So I had to copy the file into the /deployments/heroku directory. All good now.

2. Buildpack looks wrong:

remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to em-retros1.

**Comment by loganripplinger** [comment]
I have the same issue.

**Comment by emgord** [comment]
I am also having the same issue

**Comment by emgord** [comment]
I was able to get the deploy script to work by first installing the npm packages from the web directory, and then running the package.sh script in the root. This created a package.zip of the build ready for deployment on each platform, and the instructions worked from there.

**Comment by textbook** [comment]
I just successfully ran `./deploy.sh <client-app> <server-app>` in `/package/heroku` using `postfacto-3.0.1.zip` file from [the release](https://github.com/pivotal/postfacto/releases/tag/3.0.1). There was no problem with script location or buildpack detection.

If you're trying to do this from a clone of the repo or the source code download then yes, you'll need to run `package.sh` to actually build the deployment package. If you have `deploy-heroku.sh`, rather than `heroku/deploy.sh`, you're not using the right asset.

**Comment by textbook** [comment]
@seadowg do you know what happened to the `package.zip` from the [3.1.3 release](https://github.com/pivotal/postfacto/releases/tag/3.1.3)? It looks like it got created in [the build](https://travis-ci.org/pivotal/postfacto/builds/508896266) but never made it to the release.

**Comment by seadowg** [comment]
No idea! In `.travis.yml` you'll see that it only "deploys" on tags. It could be that the key being used is tied to my account so you need to regenerate. A lot of Github plugins tie everything to a user (annoying I know) so potentially making a shared Github account for things like that could be helpful.

**Comment by textbook** [comment]
I've just cut a new release (3.2.0) that has the zipped package file correctly uploaded to it - let me know if you have any problems deploying to Heroku from that.
