### ISSUE TITLE
Local development docker compose

### ISSUE THREAD

**Issue by mrichins** [pivotal/postfacto#182]
Hey! 

So I am exploring running postfacto internally for my own team, and have spent some time writing dockerfiles for the web and api services, and pulling them together with a docker-compose.yml. While I might use this for serving my own team, this might be useful for local development purposes (or maybe running in K8S) Not sure what your thoughts are.

**Purpose**: Enable simple setup and local development in docker.
**Benefits**: Encapsulating dependencies in a docker container means local development only requires docker instead of specific versions of node and ruby.

I am more than happy to submit a PR once I am done, if this is something you are interested in.

**Comment by textbook** [comment]
Hi Mason, thanks for contributing!

There is already a [development container](https://hub.docker.com/r/postfacto/dev) for Docker usage, which has Node and Ruby preinstalled; it's defined in `docker/dev/Dockerfile`. This container is also used by the Travis build.

You can run this by running the `docker.sh` script in the repo root, then running `cd postfacto/ && ./deps.sh` once the container starts. This should give you an environment where you can work on the app, run it for local dev with `./run.sh` or test it with `./test.sh`. This uses a local SQLite database rather than MySQL/Postgres and the in-memory mode of ActionCable rather than Redis.

There is more information about this in https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md, but maybe that link is not obvious enough in the root README.

In terms of a Docker compose network, I did also look at spinning up a network to bring in real Postgres and Redis images. We are currently (see #174) working on changing the default deployment topology to run a single app, rather than two separate apps, so we didn't pursue that at the time. You can see the WIP here: https://github.com/textbook/postfacto/tree/feat-combine-artifacts/docker/release.

Let me know if there's any more information you need, or if you have other ideas you'd like to discuss.
