### ISSUE TITLE
add a simple way to generate an api key

### ISSUE THREAD

**Issue by vchrisb** [pivotal/postfacto#186]
I'm using postfacto (https://retros.cfapps.io) and implemented a small slack bot to interact with it. Currently I extracted my token via chrome inspect.
Having an option to generate a token would be helpful!

**Comment by textbook** [comment]
Thanks for getting in touch! I'd be interested to hear what your use case is here; we've been discussing how we integrate with external services within the product team, and are currently thinking about more of a webhook-based approach, rather than encouraging direct API usage. If you have feedback around that, I've just opened #196 to discuss it.

**Comment by butzopower** [comment]
Closing as we hope to move towards a webhook-based approach rather than direct API access.
