### ISSUE TITLE
Increase the hit area of reactions

### ISSUE THREAD

**Issue by wlindner** [pivotal/postfacto#301]
Have you ever been in a retro using postfacto and had the annoyance of the screen suddenly scrolling to highlight a clicked item because someone was trying to click the ❤️ reaction, but missed and hit the retro item instead? This happens all the time during retros I'm in and it's really annoying. It slows down retros, it's confusing for new users, and it should be a relatively simple fix.

Postfacto would be greatly improved if the click area for a reaction was larger.

I made an example of how it could work here: https://codepen.io/wlindner/full/PoZMWeB

Feedback is greatly appreciated.

**Comment by textbook** [comment]
This was already implemented in [4.2.0](https://github.com/pivotal/postfacto/releases/tag/4.2.0), see e.g. [this deployment](https://postfacto-postgres-only.herokuapp.com/retros/demo-retro/join/9UofV5m7rb74iCtq4dlYEYuyFc0MdbLm). It's also been highlighted on hover since [3.2.0](https://github.com/pivotal/postfacto/releases/tag/3.2.0) to make it clearer when a click will like or edit the item, rather than selecting it.

**Comment by wlindner** [comment]
Woohoo! That's great. I'm glad it's fixed. 🎉
