### ISSUE TITLE
Run postfacto Locally.

### ISSUE THREAD

**Issue by christianmatei** [pivotal/postfacto#320]
Hi team. I need your help.

I have the task to run post facto in a local environment. I do not have access to any containers. I do have access to VM (Linux or Windows) to run on it. The closer I got to it is using docker locally and run post facto dev, is there any recommendation or instructions I can run on Linux directly? if yes, can you provide the steps or instructions?

Thank you 
Any help is greatly appreciated.

**Comment by textbook** [comment]
Firstly, note that the `postfacto/dev` container is the development environment, used for local dev and CI. The container for actually running an instance of Postfacto is `postfacto/postfacto` 🐳

It is possible to run a Postfacto directly on Linux, although we don’t support it directly. There are various performance and security considerations for managing any app on a VM, which is why we recommend using managed environments like VMware Tanzu, Heroku or Kubernetes, but as a simple guide:

- You’ll need to have Ruby (the app is tested with 2.6.3) and Bundler (`gem install bundler:2.0.1`) available on the VM.

- You can grab the `package.zip` from the [latest release](https://github.com/pivotal/postfacto/releases/latest). The `assets/` directory contains the Ruby server app and the bundled React client.

- You can edit `assets/client/config.js` with any client configuration you need (e.g. if you need to change the websocket port or to enable analytics).

- Paths to the database (Postgres or MySQL) and message queue (Redis) can be provided by the environment variables `DATABASE_URL` and `REDIS_URL` respectively.
    - _Alternatively you can set `USE_POSTGRES_FOR_ACTION_CABLE=true` and just have a Postgres `DATABASE_URL`._

- Once the database is available run a few commands to set it up:
 
    ```
    bundle exec rake db:create db:migrate
    bundle exec rake admin:create_user ADMIN_EMAIL=<email> ADMIN_PASSWORD=<password> 
    ```

- Then you can start the app with [rails server](https://guides.rubyonrails.org/command_line.html#rails-server):

    ```
    bundle exec rails server -e production -p <port> -b <ip>
    ```

As mentioned above, though, there are other considerations to self-managing the app on a VM. I'd recommend having a look into more through guidance to get this running properly, e.g. https://gorails.com/guides.

**Comment by christianmatei** [comment]
Thank you for the information. I will give it a go for sure.

**Comment by christianmatei** [comment]
Hi textbook,

Thank you so much for all the clarification provided. I still need some clarifications. I hope that you can expand on the:

Paths to the database (Postgres or MySQL) and message queue (Redis) can be provided by the environment variables DATABASE_URL and REDIS_URL respectively.

Alternatively you can set USE_POSTGRES_FOR_ACTION_CABLE=true and just have a Postgres DATABASE_URL.

Thank you

**Comment by christianmatei** [comment]
I mean, do I need to create a DB instance with tables etc etc. or I just install a Db and then create the DB URL ?

**Comment by christianmatei** [comment]
@textbook (Jonathan Sharpe)

**Comment by textbook** [comment]
We can't tell exactly what work you'll need to do, because we don't know how you're planning to set this up. From Postfacto's perspective, these are [_backing services_][1]. It doesn't know whether they're:

- on the same local VM (i.e. you're going to do the installation, management and configuration yourself);
- somewhere else in your organisation (talk to your DB admins); or 
- being hosted and managed for you by a third party (e.g. the Postgres team maintain [this list](https://www.postgresql.org/support/professional_hosting/) of providers).

All Postfacto does is connect to that service using the supplied connection string (for Postgres, for example, it would look like `postgresql://user:password@netloc:port/dbname`) when it starts up.

Note that you don't need to create any _tables_ in your database, though; Postfacto will create the tables it needs when it starts up (using the migrations specified in `db/migrate/`).

If you _do_ want to run any or all of MySQL, Postgres and Redis on the local VM, you'll have to go to the relevant documentation to understand how to install and correctly configure that software.

  [1]: https://12factor.net/backing-services

**Comment by christianmatei** [comment]
Thank you so much. Its a simple stand alone post facto. Hence all is going to be on one machine. Ideea is that we run with our team(5-7 people) local postfacto. Therefore, nothing complicated. All under one machine is perfect for us. The machines are under internal netowork.  I will go trough the docs. I understand the support and I wish to thank you so much for all the clarifcation provided.
