### ISSUE TITLE
Deployment is successful but app is not running

### ISSUE THREAD

**Issue by saurabh1969** [pivotal/postfacto#418]
Followed the process for Heroku deployment : https://github.com/pivotal/postfacto/blob/master/deployment/README.md

1. Downloaded code 4.3.11 version : https://github.com/pivotal/postfacto/releases
2. Unzip and cd into package/heroku
3. Deploy using deploy.sh my-postfacto (windows cmd)

No issues while deployment . But cannot see app running

![image](https://user-images.githubusercontent.com/20818439/143568656-8baf4037-c486-454d-b1a5-b4cc3d534a38.png)

Logs:

![image](https://user-images.githubusercontent.com/20818439/143568588-00a1f618-1e32-440c-a377-445629639ac3.png)

**Comment by samanthamar** [comment]
Same issue here.

**Comment by saurabh1969** [comment]
On manually trying all steps,get this error:

![image](https://user-images.githubusercontent.com/20818439/143673548-fe66a069-9e7e-4941-9ecb-c58628c7724b.png)

**Comment by textbook** [comment]
I couldn't replicate this, I used the `heroku/deploy.sh` script following the instructions and it worked fine. From that last screenshot specifically you're trying to push from the wrong directory, `heroku/` rather than `assets/` (note the `pushd`), so aren't including the files that the Ruby buildpack is looking for (reference: https://devcenter.heroku.com/articles/ruby-support#general-support-activation).

**Comment by saurabh1969** [comment]
@textbook  Thanks for pointing out that. I was pushing from different folder while doing steps manually.I went to assets/ folder and i did all steps, it worked. One modification i did was not to use the buildpack which you guys have provided while creating the app.I used heroku default Ruby build back. 

Old: heroku create postfacto-chariot --buildpack https://github.com/heroku/heroku-buildpack-ruby.git --region us

New: heroku create moc-chariot --region us

Any reasons you guys weren't using heroku ruby buildpack?

**Comment by textbook** [comment]
> Any reasons you guys weren't using heroku ruby buildpack?

https://github.com/heroku/heroku-buildpack-ruby _is_ the Heroku Ruby buildpack.

The deploy script uses `--buildpack https://github.com/heroku/heroku-buildpack-ruby.git#v227` to pin a _specific version_ of the buildpack, otherwise changes to the runtime or dependencies in the buildpack could mean the app fails to deploy at some point in the future.

**Comment by saurabh1969** [comment]
@textbook  Thanks for the help.
